### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by kleinjm** [cmer/alfred-ticktick#2]
I set up the env vars for username and password. I also ran the script locally and I think the API no longer works

**Comment by ctwhome** [comment]
I guess you need to add the user and the password inside the add_to_ticktick file 
![image](https://user-images.githubusercontent.com/4195550/76597798-9c4ebd00-6501-11ea-8d91-420d0413e5c5.png)

**Comment by bookwormat** [comment]
the login seems to fail. 
This is the error message:

```
[08:40:45.503] Add to TickTick[Keyword] Processing complete
[08:40:45.504] Add to TickTick[Keyword] Passing output 'foo' to Run Script
[08:40:46.438] Add to TickTick[Run Script] Processing complete
[08:40:46.450] Add to TickTick[Run Script] Passing output '{"title":"An error occured","subtitle":"Login failed. Exiting."}

```

**Comment by bookwormat** [comment]
Turns out the script works fine for me after all. I had to reset my password and then it works. I was logged in fine, not sure if the failed Alfred logins made them block the password. 

However: one big improvement to this script would be if there was a failure sound when the script fails. Currently, I can add tasks all day and never realize that my tasks are not actually added.
